import type { DonationCause, Order } from "@/lib/types"
import type { PaymentRecord } from "@/lib/payments/types"

const now = new Date()
const iso = (daysAgo: number) => new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000).toISOString()

export const DEFAULT_DONATION_CAUSES: DonationCause[] = [
  {
    id: "default-health",
    title: "Health & Blood Drive",
    description: "Support community blood donation campaigns and health outreach.",
    image: "",
    targetAmount: 500000,
    currentAmount: 125000,
    isActive: true,
    createdAt: iso(40),
    updatedAt: iso(2),
  },
  {
    id: "default-environment",
    title: "Environment & Tree Planting",
    description: "Fund clean-ups, tree planting, and environmental education.",
    image: "",
    targetAmount: 350000,
    currentAmount: 82000,
    isActive: true,
    createdAt: iso(38),
    updatedAt: iso(5),
  },
  {
    id: "default-community",
    title: "Community Service",
    description: "Help educational support, youth empowerment, and outreach visits.",
    image: "",
    targetAmount: 400000,
    currentAmount: 96000,
    isActive: true,
    createdAt: iso(36),
    updatedAt: iso(1),
  },
]

export const SAMPLE_PAYMENTS: PaymentRecord[] = [
  {
    id: "sample-don-1",
    kind: "donation",
    title: "Health & Blood Drive",
    payerName: "Anonymous Donor",
    payerEmail: "donor@example.com",
    amount: 25000,
    currency: "MWK",
    status: "paid",
    method: "paychangu",
    txRef: "LEO-SAMPLE-DON-001",
    date: iso(6),
    detail: "Public donation via PayChangu",
    sample: true,
  },
  {
    id: "sample-don-2",
    kind: "donation",
    title: "Environment & Tree Planting",
    payerName: "Chikondi Banda",
    payerEmail: "chikondi@example.com",
    amount: 10000,
    currency: "MWK",
    status: "pending",
    method: "paychangu",
    txRef: "LEO-SAMPLE-DON-002",
    date: iso(1),
    detail: "Awaiting PayChangu confirmation",
    sample: true,
  },
  {
    id: "sample-mem-1",
    kind: "membership",
    title: "Yearly membership",
    payerName: "Leo Mzota",
    payerEmail: "leo.mzota@example.com",
    amount: 10000,
    currency: "MWK",
    status: "paid",
    method: "paychangu",
    txRef: "LEO-SAMPLE-MEM-001",
    date: iso(12),
    detail: "Coverage for this year",
    sample: true,
  },
  {
    id: "sample-mem-2",
    kind: "membership",
    title: "Monthly membership",
    payerName: "Jane Banda",
    payerEmail: "jane.banda@example.com",
    amount: 1500,
    currency: "MWK",
    status: "paid",
    method: "offline",
    txRef: "LEO-SAMPLE-MEM-002",
    date: iso(4),
    detail: "Cash recorded by admin",
    sample: true,
  },
  {
    id: "sample-join-1",
    kind: "joining",
    title: "Joining fee",
    payerName: "Prospective Leo",
    payerEmail: "join@example.com",
    amount: 5000,
    currency: "MWK",
    status: "paid",
    method: "paychangu",
    txRef: "LEO-SAMPLE-JOIN-001",
    date: iso(3),
    detail: "Once-off joining fee",
    sample: true,
  },
  {
    id: "sample-shop-1",
    kind: "order",
    title: "District 45 T-shirt × 1",
    payerName: "Leo Mzota",
    payerEmail: "leo.mzota@example.com",
    amount: 17000,
    currency: "MWK",
    status: "paid",
    method: "paychangu",
    txRef: "LEO-SAMPLE-SHOP-001",
    date: iso(2),
    detail: "MUBAS campus pickup",
    sample: true,
  },
]

export const SAMPLE_ORDERS: Order[] = [
  {
    id: "sample-order-1",
    userId: "sample",
    items: [{ productId: "tshirt-green", name: "District 45 T-shirt", quantity: 1, price: 15000 }],
    subtotal: 15000,
    deliveryFee: 2000,
    total: 17000,
    currency: "MWK",
    status: "processing",
    paymentMethod: "paychangu",
    paymentStatus: "paid",
    txRef: "LEO-SAMPLE-SHOP-001",
    customerName: "Leo Mzota",
    customerEmail: "leo.mzota@example.com",
    phone: "+265 999 123 456",
    shippingAddress: "MUBAS campus pickup",
    createdAt: iso(2),
    updatedAt: iso(2),
  },
  {
    id: "sample-order-2",
    userId: "sample",
    items: [{ productId: "cap-red", name: "Leo Club Cap", quantity: 1, price: 8000 }],
    subtotal: 8000,
    deliveryFee: 2000,
    total: 10000,
    currency: "MWK",
    status: "completed",
    paymentMethod: "paychangu",
    paymentStatus: "paid",
    txRef: "LEO-SAMPLE-SHOP-002",
    customerName: "Jane Banda",
    customerEmail: "jane.banda@example.com",
    shippingAddress: "Blantyre",
    createdAt: iso(18),
    updatedAt: iso(10),
  },
]

export const SAMPLE_PAYMENT_TOTALS = {
  donationTotal: 125000,
  donationThisMonth: 25000,
  feesCollected: 80000,
  joiningCollected: 15000,
  shopCollected: 17000,
  pendingDonations: 2,
}
